apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gaffer.fullname" . }}-tservers
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: tserver
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.accumulo.tabletServers.replicaCount }}
  serviceName: {{ template "gaffer.fullname" . }}-tservers
  selector:
    matchLabels:
      {{- include "gaffer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tserver
  template:
    metadata:
      labels:
        {{- include "gaffer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tserver
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/accumulo/config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: accumulo-tserver
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        args:
        - tserver
        env:
        - name: ACCUMULO_CONF_DIR
          value: /etc/accumulo/
        volumeMounts:
        - name: config
          mountPath: /etc/accumulo/
          readOnly: true
        resources:
          {{- toYaml .Values.accumulo.tabletServers.resources | nindent 10 }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "gaffer.fullname" . }}-accumulo-config
          optional: false
      {{- with .Values.accumulo.tabletServers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.tabletServers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.tabletServers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
