# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alpine:
  repository: alpine
  tag: 3.10.2
  imagePullPolicy: IfNotPresent

namenode:
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  ports:
    http: 9870
    https: 9871
    clientRpc: 8020
    serviceRpc: 8021
    lifelineRpc: 8022
  dataVolumes:
    count: 1
    pvcTemplateSpec:
      storageClassName: null
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  extraEnvVars: {}
    # Example usage:
    # HADOOP_HEAPSIZE_MIN: 128m
    # hadoop.heapsize.min: 128m

datanode:
  nodeCount: 3
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  ports:
    http: 9864
    https: 9865
    data: 9866
    ipc: 9867
  dataVolumes:
    count: 1
    pvcTemplateSpec:
      storageClassName: null
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  extraEnvVars: {}
    # Example usage:
    # HADOOP_HEAPSIZE_MIN: 128m
    # hadoop.heapsize.min: 128m

shell:
  enabled: true
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

config:
  path: /etc/hadoop/conf
  coreSite: {}
  hdfsSite:
    dfs.replication: 3
    hadoop.security.authorization: true
  rackAwareness:
    serviceAccountName:
    nodeTopologyLabel: topology.kubernetes.io/zone

secrets:
  path: /etc/hadoop/secrets
  files: {}

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  host: ""
  # For Traefik:
  # pathPrefix: /hdfs/
  # For Nginx:
  pathPrefix: "/hdfs/(.*)"

postInstallCommands: []
# - hadoop fs -mkdir -p /accumulo
# - hadoop fs -chown accumulo /accumulo
# - hadoop fs -chmod 700 /accumulo
# - hadoop fs -ls /

networkPolicy:
  enabled: true
