apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gaffer.fullname" . }}-monitor
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
spec:
  replicas: {{ .Values.accumulo.monitor.replicaCount }}
  selector:
    matchLabels:
      {{- include "gaffer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: monitor
  template:
    metadata:
      labels:
        {{- include "gaffer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: monitor
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/accumulo/config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: accumulo-monitor
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        args:
        - monitor
        env:
        - name: ACCUMULO_CONF_DIR
          value: /etc/accumulo/
        volumeMounts:
        - name: config
          mountPath: /etc/accumulo/
          readOnly: true
        ports:
        - name: http
          protocol: TCP
          containerPort: 9995
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        resources:
          {{- toYaml .Values.accumulo.monitor.resources | nindent 10 }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "gaffer.fullname" . }}-accumulo-config
          optional: false
      {{- with .Values.accumulo.monitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.monitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.monitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
