{{- /*

Copyright 2020 Crown Copyright

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/ -}}

{{- define "gaffer.storeProperties" -}}

{{- if .Values.accumulo.enabled }}
gaffer.store.class=uk.gov.gchq.gaffer.accumulostore.AccumuloStore
gaffer.store.properties.class=uk.gov.gchq.gaffer.accumulostore.AccumuloProperties
accumulo.instance={{ .Values.accumulo.instanceId }}
accumulo.zookeepers={{ template "gaffer.callSubChartTemplate" (list . "accumulo" "accumulo.zookeepers") }}
accumulo.user={{ required "Please set api.user to the name of the user that the REST API should authenticate to Accumulo with" .Values.api.user }}


{{- /* Make sure that the Accumulo user that the API will be using will be created */}}
{{- if hasKey .Values.accumulo.config.userManagement.users .Values.api.user }}
  {{- $apiUserInfo := index .Values.accumulo.config.userManagement.users .Values.api.user }}
accumulo.password={{ required (print "Password required for API's Accumulo User: " .Values.api.user ". Please set: accumulo.config.userManagement.users." .Values.api.user ".password") $apiUserInfo.password }}
  {{- /* Make sure the user used by the API will have the right permissions */}}
  {{- if not (hasKey $apiUserInfo "permissions") }}
    {{- fail (print "API Accumulo User: " .Values.api.user " needs to have READ and WRITE permission to the " .Values.graph.config.graphId " table!") }}
  {{- else if not (hasKey $apiUserInfo.permissions "table") }}
    {{- fail (print "API Accumulo User: " .Values.api.user " needs to have READ and WRITE permission to the " .Values.graph.config.graphId " table!") }}
  {{- else }}
    {{- $apiUserGraphTablePermissions := required (print "API Accumulo User: " .Values.api.user " needs to have READ and WRITE permission to the " .Values.graph.config.graphId " table!") (index $apiUserInfo.permissions.table .Values.graph.config.graphId) }}
    {{- if or (not (has "READ" $apiUserGraphTablePermissions)) (not (has "WRITE" $apiUserGraphTablePermissions)) }}
      {{- fail (print "API Accumulo User: " .Values.api.user " needs to have READ and WRITE permission to the " .Values.graph.config.graphId " table!") }}
    {{- end }}
  {{- end }}
{{- else if eq "root" .Values.api.user }}
accumulo.password={{ .Values.accumulo.config.userManagement.rootPassword }}
{{- else }}
{{ fail (print "The API's Accumulo user called " .Values.api.user " needs to be defined in accumulo.config.userManagement.users") }}
{{- end }}


{{- else if not (or (hasKey .Values.graph.storeProperties "gaffer.store.class") (hasKey .Values.graph.storeProperties "gaffer.store.properties.class")) }}
gaffer.store.class=uk.gov.gchq.gaffer.mapstore.MapStore
gaffer.store.properties.class=uk.gov.gchq.gaffer.mapstore.MapStoreProperties

{{- end }}
{{- range $property, $value := .Values.graph.storeProperties }}
{{ $property }}={{ $value }}
{{- end }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gaffer.fullname" . }}-store-properties
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: store-properties
type: Opaque
data:
  store.properties: {{ include "gaffer.storeProperties" . | b64enc | quote }}
