apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "hdfs.fullname" . }}-namenodes
  labels:
    {{ include "hdfs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hdfs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: namenode
  policyTypes:
  - Ingress
  ingress:
  # Allow clients to access client RPC and HTTP servers
  - ports:
    - port: http
    - port: https
    - port: client-rpc
  # Allow NameNode and DataNodes to access Service and Lifeline RPC Servers
  - from:
    - podSelector:
        matchLabels:
          {{- include "hdfs.selectorLabels" . | nindent 10 }}
    ports:
    - port: service-rpc
    - port: lifeline-rpc
